# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'meiyan' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#  pod 'AFNetworking', '~> 3.0'
# opengl滤镜库
  pod 'GPUImage'
#  约束布局 SnapKit
  pod 'SnapKit', '~> 5.0.0'
#  图片选择器
#  pod "BSImagePicker", "~> 2.8"
#  指示剂 loading
  pod 'NVActivityIndicatorView'
  pod 'NVActivityIndicatorView/AppExtension'
#  模仿图android的图片管理库
  pod 'R.swift'


  # Pods for meiyan

  target 'meiyanTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'meiyanUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
